### ISSUE TITLE
Error trying to open trace_random_callstacks.json.gz

### ISSUE THREAD

**Issue by graphicsMan** [iwanders/scalopus#21]
If I try to open trace_random_callstacks.json.gz from chrome://tracing, I get the following error:

While importing:
Error: Couldn't create an importer for the provided eventData.
    at Import.createImporter_ (chrome://tracing/tracing.js:2020:2071)
    at chrome://tracing/tracing.js:2015:167
    at Task.run (chrome://tracing/tracing.js:3262:95)
    at runAnother (chrome://tracing/tracing.js:3265:371)
    at runTask (chrome://tracing/tracing.js:3027:57)
    at processIdleWork (chrome://tracing/tracing.js:3032:116)
    at window.requestIdleCallback.timeout (chrome://tracing/tracing.js:3025:81)

**Comment by iwanders** [comment]
Hi, @graphicsMan, I presume you're talking about this [trace_random_callstacks.json.gz](https://github.com/iwanders/scalopus/blob/master/doc/trace_random_callstacks.json.gz)? I just tested the file, it for sure works in `Version 90.0.4430.93 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)`. Quick google shows [this issue](https://github.com/catapult-project/catapult/issues/2378) in the catapult project, the trace viewer is part of the catapult project. Cause there was a corrupt file.

Here's the md5sum for the [trace_random_callstacks.json.gz](https://github.com/iwanders/scalopus/blob/master/doc/trace_random_callstacks.json.gz) file I mentioned:
```
md5sum trace_random_callstacks.json.gz 
70e517631f4dbbae0dad5c3f2c2169d1  trace_random_callstacks.json.gz
```
This should allow you to rule out data corruption. I haven't heard any problems using the latest google chrome either, so if it's not a malformed file I'm not too sure what's causing this.

**Comment by artrointel** [comment]
I do suffering with the identical error log.

**Comment by iwanders** [comment]
Which version of Chrome is this happening on? I'm on `Version 91.0.4472.77` currently and it still opens without a problem for me.

**Comment by artrointel** [comment]
> Which version of Chrome is this happening on? I'm on `Version 91.0.4472.77` currently and it still opens without a problem for me.

First of all, I just resolved the issue now at least my side. 
I guess this is not the Chrome issue, but the legacy version of systrace.
I got the systrace file from android device monitor which is deprecated long long time ago.
format of the systrace file from the monitor also deprecated. So, Chrome couldn't read the file.

Now I get systrace.py from Android SDK and it gives readable.

Thanks

**Comment by iwanders** [comment]
I'm not sure how any of that relates to this repository. This tracing tool writes its own json files with trace events. Issues originating from trace files written by Android's device monitor or systrace should not be reported here.

I presume this is also the case with the original post here. I'm glad it is resolved :+1: , closing this issue.
